version: "3.1"

services:
  postgres:
    image: postgres:12.9
    ports:
      - "7432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: csvbase
    networks:
      csvbase:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  csvbase:
    build: .
    environment:
      CSVBASE_DB_URL: 'postgresql://postgres:password@postgres:5432/csvbase'
    ports:
      - "6001:6001"
    networks:
      csvbase:
    depends_on:
      postgres:
        condition: service_healthy

networks:
  csvbase:
    driver: bridge
