name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CSVBASE_DB_URL: postgresql+psycopg2://csvbase:csvbase@localhost/csvbase
      CSVBASE_SECRET_KEY: 'snakeoil'
      GITHUB_ACTIONS: 'yes'

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: csvbase
          POSTGRES_PASSWORD: csvbase
          POSTGRES_DB: csvbase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install required ubuntu packages
      run: sudo apt-get update && sudo apt-get install -y libsystemd-dev
    - name: Use cache of pip downloads
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install tox
      run: pip install tox
    # - name: Use cache of tox
    #   uses: actions/cache@v2
    #   with:
    #     path: .tox
    #     key: ${{ runner.os }}-tox
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    - name: Tox
      run: tox
