name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Use cache of pip downloads
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('test-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install tox
      run: pip install tox
    - name: Use cache of tox
      uses: actions/cache@v1
      with:
        path: src/server/.tox
        key: ${{ runner.os }}-tox
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Tox
      run: tox
